### ISSUE TITLE
TM1 Relaunch Education

### ISSUE THREAD

**Issue by raposok** [raposok/TaskBoard#5]
- [ ] Who are stakeholders?
   - Trevor: Executive sponsor
   - Robert: Product owner
   - ???: Client(s)  -> who can we show our deliverables to for feedback?
   - Scrum master: Kelly?   unblock obstacles, collect status, master-servant role
   - Team: Robbie and Andy
- [ ] What are the deliverables?
   - wiki pages?
   - website?
   - documentation? education material?
   - TM1 reports?
   - specific TM1 functionality?
- [ ] What is the timeframe?
   - deadlines
- [ ] How is the project being tracked?
   - proposed zenhub
